- name: Install NTP service
  yum:
    name: ntp
    state: installed
  ignore_errors: true

- name: Make sure the NTP service is enabled
  service:
    name: ntpd
    enabled: yes
  ignore_errors: true

- name: Set swappiness to 0
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    reload: yes
    ignoreerrors: yes

- name: Stop the iptables service
  service:
    name: iptables
    state: stopped
  ignore_errors: true

- name: Disable the iptables firewall service
  service:
    name: iptables
    enabled: no
  ignore_errors: true

- name: Disable Transparent Huge Pages until the next reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  args:
    removes: /sys/kernel/mm/transparent_hugepage/enabled


- name: Install epel
  yum:
    name: epel-release
    state: installed
  ignore_errors: true


- name: Disable selinux
  selinux:
    state: disabled

- name: Check is umask Value exists
  command: grep "umask 0022" /etc/profile
  register: umask
  always_run: True
  ignore_errors: True
  changed_when: False

- name: Updating umask Value
  shell: |
    echo umask 0022 >> /etc/profile
  when: umask.rc != 0

- name: Downloading Ambari YUM Repository Configuration File
  get_url: url='{{ ambari_repo_url }}' dest='/etc/yum.repos.d/ambari.repo' mode=0644

- name: Copy hosts.txt content to /etc/hosts if it doesnot exists
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ item }}"
    regexp: "{{ item }}"
  become: True
  with_lines: cat {{ playbook_dir }}/roles/prerequisites/files/resources/hosts.txt
  tags: copy_hosts
