---

# - name: "Copy Cluster Configuration Blueprint"
#   copy: src=Blueprint.json dest=/tmp/Blueprint.json

- name: "installing mysql driver to Ambari"
  yum:
    name: mysql-connector-java
    state: present
  tags: install_mysql_jar

- name: "Adding mysql driver to ambari"
  shell: ambari-server setup --jdbc-db mysql --jdbc-driver /usr/share/java/mysql-connector-java.jar
  become: true
  tags: add_mysql_jar

- name: "Copy Blueprint Templates"
  template: src={{ item.name }} dest=/tmp/{{ item.dest }}
  with_items:
    - { name: 'HDP.json.j2', dest: 'HDP.json' }
    - { name: 'HDP-UTILS.json.j2', dest: 'HDP-UTILS.json' }
    - { name: 'Host_Mapping.json.j2', dest: 'Host_Mapping.json' }
    - { name: 'Blueprint.json.j2', dest: 'Blueprint.json' }
  tags:
    - HDP Repository File
    - HDP-UTILS Repository File
    - Host Template File

- name: "Replacing Extra Commas in Host_Mapping.json"
  replace:
    path: /tmp/Host_Mapping.json
    regexp: '},]'
    replace: '}]'
    backup: yes

- name: Register Stack Definition with ambari server by executing below command
  shell: |
        curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/blueprints/two-node-hdp?validate_topology=false -d @/tmp/Blueprint.json

- name: Setup HDP repo via REST API.
  shell: |
        curl -H "X-Requested-By: ambari" -X PUT -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/stacks/HDP/versions/2.6/operating_systems/redhat7/repositories/HDP-2.6.4.0 -d @/tmp/HDP.json

- name: Setup HDP-UTILS repo via REST API.
  shell: |
        curl -H "X-Requested-By: ambari" -X PUT -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/stacks/HDP/versions/2.6/operating_systems/redhat7/repositories/HDP-UTILS-1.1.0.22 -d @/tmp/HDP-UTILS.json

- name: Starting HDP cluster Installation using Component Layout
  shell: |
        curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/clusters/{{ cluster_name }} -d @/tmp/Host_Mapping.json
