---


- name: "Copy Blueprint Templates"
  template: src={{ item.name }} dest=/tmp/{{ item.dest }}
  with_items:
    - { name: 'Blueprint.json.j2', dest: 'Blueprint.json' }
    - { name: 'HDF.json.j2', dest: 'HDF.json' }
    - { name: 'HDF-UTILS.json.j2', dest: 'HDF-UTILS.json' }
    - { name: 'Host_Mapping.json.j2', dest: 'Host_Mapping.json' }
  tags:
    - HDF Repository File
    - HDF-UTILS Repository File
    - Host Template File

- name: "Replacing Extra Commas in Host_Mapping.json"
  replace:
    path: /tmp/Host_Mapping.json
    regexp: '},]'
    replace: '}]'
    backup: yes

- name: Register Stack Definition with ambari server by executing below command
  shell: |
        curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/blueprints/two-node-HDF -d @/tmp/Blueprint.json

- name: Setup HDF repo via REST API.
  shell: |
        curl -H "X-Requested-By: ambari" -X PUT -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/stacks/HDF/versions/3.1/operating_systems/redhat7/repositories/HDF-3.1.1.0 -d @/tmp/HDF.json

- name: Setup HDF-UTILS repo via REST API.
  shell: |
        curl -H "X-Requested-By: ambari" -X PUT -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/stacks/HDF/versions/3.1/operating_systems/redhat7/repositories/HDP-UTILS-1.1.0.21 -d @/tmp/HDF-UTILS.json

- name: Starting HDF cluster Installation using Component Layout
  shell: |
        curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://{{ groups["ambari_node"][0] }}:8080/api/v1/clusters/{{cluster_name}} -d @/tmp/Host_Mapping.json
